apiVersion: apps/v1
kind: Deployment
metadata:
  name: survey-app-deployment
  labels:
    app: survey-app
spec:
  replicas: 3 # Number of pod replicas
  selector:
    matchLabels:
      app: survey-app
  template:
    metadata:
      labels:
        app: survey-app
    spec:
      containers:
        - name: survey-app-container
          image: jashanveer/survey-app:latest # Your Docker image
          ports:
            - containerPort: 80 # Port exposed by your container
