# Dhruvi Pruthvisinh Rathod - G01465151
# Jashanveer Singh - G01477180
# Namita Chougule – G01473740

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-form-deployment
  labels:
    app: user-form
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-form
  template:
    metadata:
      labels:
        app: user-form
    spec:
      containers:
        - name: user-form
          image: jashanveer/survey-web-app
          ports:
            - containerPort: 80
