# Dhruvi Pruthvisinh Rathod - G01465151
# Jashanveer Singh - G01477180
# Namita Chougule – G01473740

apiVersion: v1
kind: Service
metadata:
  name: user-form-service
spec:
  selector:
    app: user-form
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30088
  type: NodePort
